package pt.saltosnaspalhacadas.backend.usernotification;

public enum UserNotificationType {
    BOOKING_CREATED,
    BOOKING_ACCEPTED,
    BOOKING_DECLINED,
    BOOKING_COUNTER_PROPOSED,
    BOOKING_CUSTOMER_COUNTER_PROPOSED,
    BOOKING_CUSTOMER_COUNTER_ACCEPTED,
    BOOKING_CUSTOMER_COUNTER_DECLINED,
    BOOKING_CUSTOMER_CANCELLED,
    BOOKING_CANCELLED,
    BOOKING_REMINDER_5_DAYS
}
