CREATE TABLE client_content_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES app_users(id) ON DELETE SET NULL,
    profile_id BIGINT REFERENCES profiles(id) ON DELETE SET NULL,
    media_type VARCHAR(10) NOT NULL,
    title VARCHAR(180) NOT NULL,
    location VARCHAR(180) NOT NULL,
    event_date DATE NOT NULL,
    caption VARCHAR(800),
    media_url VARCHAR(2048) NOT NULL,
    thumbnail_url VARCHAR(2048),
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    admin_message VARCHAR(600),
    moderated_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT client_content_posts_media_type_check CHECK (media_type IN ('PHOTO', 'VIDEO')),
    CONSTRAINT client_content_posts_status_check CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED'))
);

CREATE INDEX client_content_posts_public_index
    ON client_content_posts (status, event_date DESC, id DESC);

CREATE INDEX client_content_posts_user_index
    ON client_content_posts (user_id, created_at DESC, id DESC);
