CREATE TABLE profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(120) NOT NULL,
    role VARCHAR(120) NOT NULL,
    description VARCHAR(500) NOT NULL,
    profile_image_url VARCHAR(2048),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE portfolio_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    media_type VARCHAR(10) NOT NULL,
    title VARCHAR(180) NOT NULL,
    location VARCHAR(180) NOT NULL,
    event_date DATE NOT NULL,
    media_url VARCHAR(2048) NOT NULL,
    thumbnail_url VARCHAR(2048),
    display_order INTEGER NOT NULL DEFAULT 0,
    published BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT portfolio_items_media_type_check CHECK (media_type IN ('PHOTO', 'VIDEO'))
);

CREATE INDEX portfolio_items_public_index
    ON portfolio_items (profile_id, published, display_order, event_date DESC);
