CREATE TABLE user_notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
    booking_id BIGINT REFERENCES booking_requests(id) ON DELETE SET NULL,
    type VARCHAR(40) NOT NULL,
    title VARCHAR(160) NOT NULL,
    message VARCHAR(1000) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    read_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX user_notifications_user_created_index
    ON user_notifications (user_id, created_at DESC, id DESC);

CREATE INDEX user_notifications_user_unread_index
    ON user_notifications (user_id, read_at);
