CREATE TABLE user_favorites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
    portfolio_item_id BIGINT NOT NULL REFERENCES portfolio_items(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT user_favorites_user_item_unique UNIQUE (user_id, portfolio_item_id)
);

CREATE INDEX user_favorites_user_created_index
    ON user_favorites (user_id, created_at DESC);
