CREATE TABLE booking_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
    profile_id BIGINT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    event_date DATE NOT NULL,
    event_type VARCHAR(32) NOT NULL,
    contact_name VARCHAR(120) NOT NULL,
    contact_phone VARCHAR(40) NOT NULL,
    budget DECIMAL(10, 2) NOT NULL,
    description VARCHAR(2000) NOT NULL,
    notes VARCHAR(1000),
    status VARCHAR(24) NOT NULL DEFAULT 'PENDING',
    admin_message VARCHAR(1000),
    counter_budget DECIMAL(10, 2),
    counter_event_date DATE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT booking_requests_event_type_check CHECK (
        event_type IN ('WEDDING', 'BAPTISM', 'BIRTHDAY', 'CORPORATE', 'FESTIVAL', 'PRIVATE_PARTY', 'OTHER')
    ),
    CONSTRAINT booking_requests_status_check CHECK (
        status IN ('PENDING', 'ACCEPTED', 'DECLINED', 'COUNTER_PROPOSED')
    ),
    CONSTRAINT booking_requests_budget_check CHECK (budget > 0),
    CONSTRAINT booking_requests_counter_budget_check CHECK (counter_budget IS NULL OR counter_budget > 0)
);

CREATE INDEX booking_requests_profile_status_date_index
    ON booking_requests (profile_id, status, event_date);

CREATE INDEX booking_requests_user_created_index
    ON booking_requests (user_id, created_at DESC);
