ALTER TABLE profiles ADD COLUMN featured_video_url VARCHAR(2048);

CREATE TABLE reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reviewer_name VARCHAR(120) NOT NULL,
    title VARCHAR(180) NOT NULL,
    comment VARCHAR(1200) NOT NULL,
    rating INTEGER NOT NULL,
    review_date DATE NOT NULL DEFAULT CURRENT_DATE,
    display_order INTEGER NOT NULL DEFAULT 0,
    published BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT reviews_rating_check CHECK (rating BETWEEN 1 AND 5)
);

CREATE INDEX reviews_public_index
    ON reviews (published, display_order, review_date DESC);
