import { useEffect, useState, type ChangeEvent } from 'react'
import { apiClient, uploadFile } from '../../services/apiClient'
import { getProfiles } from '../../services/profileService'
import type { Profile } from '../../types/profile'
import styles from './AdminArea.module.css'

type TokenResponse = { accessToken: string; role: 'ADMIN' | 'CUSTOMER' }
const storageKey = 'saltos.admin-token'

export function AdminArea({ onExit }: { onExit: () => void }) {
  const [token, setToken] = useState(() => sessionStorage.getItem(storageKey))
  const [message, setMessage] = useState('')
  const [profiles, setProfiles] = useState<Profile[]>([])
  const [profileImageUrl, setProfileImageUrl] = useState('')
  const [mediaUrl, setMediaUrl] = useState('')
  const refreshProfiles = () => getProfiles().then(setProfiles)
  useEffect(() => { if (token) refreshProfiles() }, [token])
  async function login(form: HTMLFormElement) { const values = new FormData(form); try { const result = await apiClient<TokenResponse>('/auth/login', { method: 'POST', body: JSON.stringify({ email: values.get('email'), password: values.get('password') }) }); if (result.role !== 'ADMIN') throw new Error('Esta conta não tem permissões de administração.'); sessionStorage.setItem(storageKey, result.accessToken); setToken(result.accessToken) } catch (error) { setMessage(error instanceof Error ? error.message : 'Erro no login.') } }
  async function upload(event: ChangeEvent<HTMLInputElement>, setUrl: (url: string) => void) { const file = event.target.files?.[0]; if (!file) return; try { const result = await uploadFile(file, token!); setUrl(result.url); setMessage('Ficheiro enviado.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Erro no envio.') } }
  async function createProfile(form: HTMLFormElement) { const values = new FormData(form); try { await apiClient('/admin/profiles', { method: 'POST', body: JSON.stringify({ slug: values.get('slug'), name: values.get('name'), role: values.get('role'), description: values.get('description'), profileImageUrl: profileImageUrl || null }) }, token!); form.reset(); setProfileImageUrl(''); refreshProfiles(); window.dispatchEvent(new Event('profiles:changed')); setMessage('Perfil criado com sucesso.') } catch (error) { setMessage(error instanceof Error ? error.message : 'Erro ao criar perfil.') } }
  async function deleteProfile(slug: string) { if (!window.confirm('Apagar este perfil e os respetivos conteúdos?')) return; try { await apiClient(`/admin/profiles/${slug}`, { method: 'DELETE' }, token!); refreshProfiles(); window.dispatchEvent(new Event('profiles:changed')); setMessage('Perfil apagado.') } catch (error) { setMessage(error instanceof Error ? error.message : 'Erro ao apagar perfil.') } }
  async function createContent(form: HTMLFormElement) { const values = new FormData(form); try { await apiClient(`/admin/profiles/${values.get('profileSlug')}/portfolio`, { method: 'POST', body: JSON.stringify({ type: values.get('type'), title: values.get('title'), location: values.get('location'), eventDate: values.get('eventDate'), mediaUrl: mediaUrl || values.get('mediaUrl'), thumbnailUrl: values.get('thumbnailUrl') || null, displayOrder: Number(values.get('displayOrder') || 0), published: true }) }, token!); form.reset(); setMediaUrl(''); setMessage('Conteúdo publicado com sucesso.') } catch (error) { setMessage(error instanceof Error ? error.message : 'Erro ao publicar conteúdo.') } }
  if (!token) return <section className={styles.login}><button onClick={onExit} type="button">← Voltar ao site</button><div><p className="eyebrow">Área reservada</p><h1>Administração</h1><p>Inicia sessão para gerir os perfis e conteúdos.</p><form onSubmit={(event) => { event.preventDefault(); login(event.currentTarget) }}><label>Email<input name="email" type="email" required /></label><label>Palavra-passe<input name="password" type="password" required /></label>{message && <p className={styles.error}>{message}</p>}<button type="submit">Entrar</button></form></div></section>
  return <section className={styles.dashboard}><div className={styles.top}><div><p className="eyebrow">Área reservada</p><h1>Painel de administração</h1></div><button type="button" onClick={() => { sessionStorage.removeItem(storageKey); setToken(null); setMessage('') }}>Terminar sessão</button></div><div className={styles.grid}><form onSubmit={(event) => { event.preventDefault(); createProfile(event.currentTarget) }}><h2>Novo perfil</h2><label>Nome<input name="name" required /></label><label>Slug<input name="slug" placeholder="dj-joao-tomas" pattern="[a-z0-9]+(?:-[a-z0-9]+)*" required /></label><label>Função<input name="role" placeholder="DJ & Animador" required /></label><label>Descrição<textarea name="description" required /></label><label>Enviar imagem<input type="file" accept="image/*" onChange={(event) => upload(event, setProfileImageUrl)} /></label><label>URL da imagem<input name="profileImageUrl" type="url" value={profileImageUrl} onChange={(event) => setProfileImageUrl(event.target.value)} /></label><button type="submit">Criar perfil</button></form><form onSubmit={(event) => { event.preventDefault(); createContent(event.currentTarget) }}><h2>Publicar conteúdo</h2><label>Slug do perfil<input name="profileSlug" placeholder="dj-joao-tomas" required /></label><label>Tipo<select name="type"><option value="PHOTO">Foto</option><option value="VIDEO">Vídeo</option></select></label><label>Título<input name="title" required /></label><label>Local<input name="location" required /></label><label>Data<input name="eventDate" type="date" required /></label><label>Enviar foto ou vídeo<input type="file" accept="image/*,video/*" onChange={(event) => upload(event, setMediaUrl)} /></label><label>URL do conteúdo<input name="mediaUrl" type="url" value={mediaUrl} onChange={(event) => setMediaUrl(event.target.value)} required /></label><label>URL da miniatura<input name="thumbnailUrl" type="url" /></label><button type="submit">Publicar</button></form></div><section className={styles.manage}><h2>Perfis existentes</h2>{profiles.length === 0 ? <p>Não existem perfis.</p> : profiles.map((profile) => <div className={styles.profileRow} key={profile.id}><span><strong>{profile.name}</strong><small>{profile.slug}</small></span><button type="button" onClick={() => deleteProfile(profile.slug)}>Apagar</button></div>)}{message && <p className={styles.success}>{message}</p>}</section></section>
}
